import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from './components/Nav/Nav';
import Navigation from './components/Navigation/Navigation';
import Providers from './providers';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${inter.className} min-h-screen bg-dark-gray grid grid-dispaly`}
        >
          {/* <header className="w-full bg-dark-gray bg-opacity-75 backdrop-blur-sm py-3 px-8 max-md:px-4 border-b-[1px] border-highlight-gray top-0 sticky"> */}
          <Nav />
          {/* </header> */}

          <main className="flex  bg-dark-gray w-full text-light-gray font-light overflow-y-scroll">
            {children}
          </main>

          <footer className="">
            <Footer />
          </footer>
        </body>
      </Providers>
    </html>
  );
}
