import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from './components/Nav/Nav';
import Navigation from './components/Navigation/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Nav />
        <main className="flex w-full bg-dark-gray h-[calc(100vh-55px)] text-light-gray font-light">
          {children}
        </main>
      </body>
    </html>
  );
}
